Add file field type
systopia/remoteeventformeditor pull request #14
Opened 2024-09-18 13:04 UTC by dontub

Corresponds to https://github.com/systopia/de.systopia.remoteevent/pull/96

systopia-reference: 26376

2024-09-23 10:25 UTC, jensschuppe requested changes

2024-09-23 10:25 UTC, jensschuppe commented on Civi/RemoteEventFormEditor/FieldType/Loader/AbstractCustomFieldTypeLoader.php
>            break;
Fall-through inconsistent now …

2024-09-23 14:05 UTC, dontub commented on Civi/RemoteEventFormEditor/FieldType/Loader/AbstractCustomFieldTypeLoader.php
>            break;
Good catch! Fixed.

2024-09-24 08:00 UTC, jensschuppe approved these changes

2024-09-24 12:44 UTC, merged